# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- twitter
- tagcloud
- clustermap
- archive

# Miscellaneous
google_analytics: UA-1239956-1
favicon: /favicon.png
twitter: 
   username: lucdew
google_plus:
fb_admins:
fb_app_id:
